config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|zh-TW/ do
    resources :users, only: %i[new create edit update]
    namespace :admin do
      resources :users, only: %i[index edit update destroy]
    end
    resources :tasks, except: %i[index] do
      collection do
        get :personal
        post :sort
      end
      member do
        patch :update_importance
      end
    end
    resources :group_tasks, only: %i[index]

    resources :notifications, only: %i[index] do
      member do
        patch :mark_as_read
      end
    end

    resources :groups, except: %i[show] do
      delete 'remove_user', on: :member
    end

    resources :reports, only: [] do
      collection do
        get :tag_usage
      end
    end

    root 'tasks#personal'

    get 'signup', to: 'users#new'
    post 'signup', to: 'users#create'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    get '/profile/edit', to: 'users#edit_profile', as: :edit_profile
    patch '/profile', to: 'users#update_profile', as: :update_profile
  end
  get '', to: redirect('/%<locale>s'), defaults: { locale: I18n.default_locale }
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  acts_as_paranoid
  has_one_attached :file

  belongs_to :user
  belongs_to :author, class_name: 'User', foreign_key: 'user_id', inverse_of: :tasks
  belongs_to :group, optional: true
  has_many :task_users, dependent: :destroy, inverse_of: :task
  has_many :shared_users, through: :task_users, source: :user
  has_many :task_tags, dependent: :destroy
  has_many :tags, through: :task_tags, dependent: :destroy
  has_many :group_tasks, dependent: :destroy
  has_many :groups, through: :group_tasks, dependent: :destroy

  enum priority: { low: 1, medium: 2, high: 3 }
  enum status: { pending: 1, in_progress: 2, completed: 3 }

  validates :title, presence: true
  validates :content, presence: true
  validates :priority, presence: true
  validates :status, presence: true
  validate :start_time_cannot_be_greater_than_or_equal_to_end_time

  # Scope in Task model
  scope :filtered_by_status, ->(status) { where(status:) if status.present? }
  scope :filtered_by_query, lambda { |query|
    cleaned_query = query.to_s.strip
    if cleaned_query.present?
      joins('LEFT OUTER JOIN task_tags ON task_tags.task_id = tasks.id')
        .joins('LEFT OUTER JOIN tags ON tags.id = task_tags.tag_id')
        .where('tasks.title ILIKE ? ', "%#{cleaned_query}%")
        .distinct
    end
  }
  scope :sorted, -> { order(priority: :desc, start_time: :asc) }
  scope :ordered_by, ->(column, direction) { order(column => direction) }
  scope :filter_by_tag, ->(tag_id) { joins(:tags).where(tags: { id: tag_id }) if tag_id.present? }

  default_scope { order(position: :asc) }
  scope :important, -> { where(important: true) }

  scope :owned_and_shared_by, lambda { |user|
    Task.left_outer_joins(:task_users)
        .where('tasks.user_id = ? OR task_users.user_id = ?', user.id, user.id)
        .distinct
  }

  scope :with_shared_count, lambda {
    select('tasks.*, (SELECT COUNT(*) FROM task_users WHERE task_users.task_id = tasks.id AND task_users.user_id != tasks.user_id) AS shared_count')
  }

  scope :for_user_groups, lambda { |user|
    joins(:groups).where(groups: { id: user.group_ids })
  }

  def human_priority
    I18n.t("enums.task.priority.#{priority}")
  end

  def human_status
    I18n.t("enums.task.status.#{status}")
  end

  def shared_count
    if groups.any?
      groups.joins(:users).where.not(users: { id: user_id }).distinct.count('users.id')
    else
      shared_users.where.not(id: user_id).count
    end
  end

  private

  def start_time_cannot_be_greater_than_or_equal_to_end_time
    return unless start_time.present? && end_time.present? && start_time >= end_time

    errors.add(:start_time, I18n.t('tasks.errors.start_time_greater_than_end_time'))
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

# This controller manages the users within the admin namespace.
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[show edit update destroy]
  before_action :find_notification, only: %i[show]
  before_action :users_by_letter, only: %i[new edit]
  before_action :set_groups_by_letter, only: %i[new create edit update]

  def personal
    base_scope = Task.owned_and_shared_by(current_user).with_shared_count

    @tasks = load_tasks(base_scope, params).sorted.page(params[:page]).per(5)

    @important_tasks = load_tasks(base_scope.important, params)

    respond_to do |format|
      format.html
      format.json do
        render json: @tasks.map { |task| calendar_serialize_task(task) }
      end
    end
  end

  def show
    if task_accessible?
      @notification.update(read_at: Time.current) if @notification.present?
    else
      redirect_to personal_tasks_path, alert: t('alert.not_found')
    end
  end

  def new
    @task = current_user.tasks.new
  end

  def edit; end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      handle_after_save_actions
      redirect_to personal_tasks_path, notice: t('.success')
    else
      flash.now[:alert] = t('alert.creation_failed')
      render :new
    end
  end

  def update
    if task_accessible?(update: true)
      if @task.update(task_params)
        handle_after_save_actions
        redirect_to personal_tasks_path, notice: t('.success')
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to personal_tasks_path, alert: t('.insufficient_permissions')
    end
  end

  def destroy
    @task.destroy
    redirect_to personal_tasks_path, notice: t('.success')
  end

  def sort
    params[:order].each do |task_order|
      task = current_user.tasks.find_by(id: task_order[:id])
      task&.update(position: task_order[:position])
    end

    head :ok
  rescue ActiveRecord::RecordNotFound
    render json: { error: t('tasks.errors.not_found') }, status: :not_found
  end

  def update_importance
    task = Task.find_by(id: params[:id])

    if task.nil?
      render json: { error: t('tasks.errors.not_found') }, status: :not_found
      return
    end

    if task.update(important: params[:important])
      head :ok
    else
      render json: { error: t('tasks.errors.update_failed') }, status: :unprocessable_entity
    end
  end

  private

  def set_task
    @task = Task.find_by(id: params[:id])
    if @task.nil?
      redirect_to personal_tasks_path, alert: t('alert.not_found')
    else
      @task_accessible = task_accessible?
    end
  end

  def task_accessible?(update: false)
    return true if current_user.id == @task.user_id

    if update
      @task.task_users.find_by(user: current_user)&.can_edit ||
        current_user.groups.joins(:tasks).exists?(tasks: { id: @task.id })
    else
      @task.shared_users.include?(current_user) ||
        @task.groups.any? { |group| group.users.include?(current_user) }
    end
  end

  def task_params
    params.require(:task).permit(
      :title, :content, :start_time, :end_time, :priority, :status, :position, :important,
      { tag_ids: [], shared_user_ids: [], group_ids: [] }, :file
    ).tap do |whitelisted|
      whitelisted[:group_ids] ||= []
    end
  end

  def handle_after_save_actions
    create_new_tag_if_needed
    attach_file_to_task
  end

  def create_new_tag_if_needed
    return if params[:task][:new_tag].blank?

    new_tag = Tag.find_or_create_by(name: params[:task][:new_tag])
    @task.tags << new_tag unless @task.tags.include?(new_tag)
  end

  def users_by_letter
    @users_by_letter = User.grouped_by_letter(exclude_id: current_user.id)
  end

  def set_groups_by_letter
    @groups_by_letter = current_user.groups.grouped_by_letter
  end

  def attach_file_to_task
    @task.file.attach(params[:task][:file]) if params[:task][:file].present?
  end

  def find_notification
    @notification = current_user.notifications.find_by(task_id: @task.id)
  end
end

app/views/tasks/_form.html.erb
<%= form_with model: @task, local: true, class: "needs-validation", data: { controller: "task-time", turbo: false } do |form| %>
  <div class="row">
    <div class="col-md-6 mb-3">
      <%= form.label :title, t('tasks.form.title'), class: "form-label" %>
      <%= form.text_field :title,
                          class: "form-control #{'is-invalid' if @task.errors[:title].any?}",
                          placeholder: t('tasks.form.placeholder.title'),
                          required: true %>
      <% if @task.errors[:title].any? %>
        <div class="invalid-feedback">
          <%= @task.errors[:title].first %>
        </div>
      <% end %>
    </div>

    <div class="col-md-6 mb-3">
      <%= form.label :priority, t('tasks.form.priority'), class: "form-label" %>
      <%= form.select :priority, Task.priorities.keys.map { |p| [t("enums.task.priority.#{p}"), p] }, {}, class: "form-select #{'is-invalid' if @task.errors[:priority].any?}" %>
      <% if @task.errors[:priority].any? %>
        <div class="invalid-feedback">
          <%= @task.errors[:priority].first %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row" data-controller="task-time">
    <div class="col-md-6 mb-3">
      <%= form.label :start_time, t('tasks.form.start_time'), class: "form-label" %>
      <div class="input-group" data-task-time-target="startTime">
        <%= form.text_field :start_time, class: "form-control datetime-picker" %>
        <% if @task.errors[:start_time].any? %>
          <div class="invalid-feedback" style="display: block;">
            <%= @task.errors[:start_time].first %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-md-6 mb-3">
      <%= form.label :end_time, t('tasks.form.end_time'), class: "form-label" %>
      <div class="input-group" data-task-time-target="endTime">
        <%= form.text_field :end_time, class: "form-control datetime-picker #{'is-invalid' if @task.errors[:end_time].any?}" %>
        <% if @task.errors[:end_time].any? %>
          <div class="invalid-feedback" style="display: block;">
            <%= @task.errors[:end_time].first %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-6 mb-3">
    <%= form.label :file, t('tasks.form.upload_file'), class: "form-label" %>
    <%= form.file_field :file, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :content, t('tasks.form.content'), class: "form-label" %>
    <%= form.text_area :content, placeholder: t('tasks.form.placeholder.content'), class: "form-control picker" %>
  </div>

  <div class="row">
    <div class="col-md-6 mb-3">
      <%= form.label :new_tag, t('tasks.form.new_tag'), class: "form-label" %>
      <%= form.text_field :new_tag, placeholder: t('tasks.form.placeholder.tag'), class: "form-control" %>
    </div>

    <div class="col-md-6 mb-3">
      <%= form.label :status, t('tasks.form.status'), class: "form-label" %>
      <%= form.select :status, Task.statuses.keys.map { |s| [t("enums.task.status.#{s}"), s] }, {}, class: "form-select" %>
    </div>
  </div>

  <div class="mb-2" data-controller="tag-buttons">
    <div class="mb-2">
      <%= t('users.form.select_mark') %>
      <button id="show-chart-button" class="btn btn-primary mx-3 mb-2" type="button"><%= t('tasks.form.show_label_usage') %></button>
    </div>
    <% Tag.all.each do |tag| %>
      <label class="btn btn-outline-primary tag-button mb-2 <%= 'active' if @task.tag_ids.include?(tag.id) %>" data-tag-buttons-target="button">
        <input type="checkbox" name="task[tag_ids][]" value="<%= tag.id %>" autocomplete="off" <%= 'checked' if @task.tag_ids.include?(tag.id) %> hidden>
        <%= tag.name %>
      </label>
    <% end %>
  </div>

  <!-- Group -->
  <% if @groups_by_letter.present? %>
    <div class="align-items-center mb-3" data-controller="group-buttons">
      <div class="mb-3">
        <p><%= t('tasks.form.choose_share_with_groups') %></p>
      </div>
      <div class="d-flex align-items-center flex-wrap mb-3">
        <span class="btn btn-success btn-sm me-2">
          <%= t('tasks.form.selected') %> <span data-group-buttons-target="totalCount" class="fw-bold">(0)</span> <%= t('tasks.form.groups') %>
        </span>
        <button class="btn btn-danger btn-sm ms-1" data-action="click->group-buttons#clearAll"><%= t('tasks.form.clear_all_selections') %></button>
      </div>
      <div class="d-flex flex-wrap">
        <% @groups_by_letter.each do |letter, groups| %>
          <div class="dropdown mb-2 me-2">
            <button class="btn btn-secondary dropdown-toggle align-items-center fixed-width" type="button" id="dropdown<%= letter %>" data-bs-toggle="dropdown" aria-expanded="false" data-group-buttons-target="letter" data-letter="<%= letter %>">
              <%= letter %>
              <span data-group-buttons-target="count" data-letter="<%= letter %>" class="badge rounded-circle bg-success bg-opacity-25 ms-2"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdown<%= letter %>">
              <% groups.each do |group| %>
                <li>
                  <label class="dropdown-item group-button d-flex align-items-center" data-action="click->group-buttons#toggle" data-group-buttons-target="button" data-letter="<%= letter %>">
                    <input type="checkbox" name="task[group_ids][]" value="<%= group.id %>" autocomplete="off" <%= 'checked' if @task.group_ids.include?(group.id) %> hidden>
                    <%= group.name %>
                  </label>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="mb-3">
      <p><%= t('tasks.form.choose_share_with_groups') %></p>
    </div>
    <div class="mb-3">
      <p><%= t('tasks.form.no_group_create') %></p>
      <%= link_to t('groups.links.create_group'), new_group_path, class: "btn btn-success text-decoration-none" %>
    </div>
  <% end %>


  <!-- Shared users -->
  <div class="align-items-center mb-3" data-controller="user-buttons">
    <div class="mb-3">
      <p><%= t('users.form.choose_share_with_other_users') %></p>
    </div>
    <div class="d-flex align-items-center flex-wrap mb-3">
      <span class="btn btn-success btn-sm me-2">
        <%= t('users.form.selected') %> <span data-user-buttons-target="totalCount" class="fw-bold">(0)</span> <%= t('users.form.peoples') %>
      </span>
      <button class="btn btn-danger btn-sm ms-1" data-action="click->user-buttons#clearAll"><%= t('users.form.clear_all_selections') %></button>
    </div>
    <div class="d-flex flex-wrap">
      <% if @users_by_letter.present? %>
        <% @users_by_letter.each do |letter, users| %>
          <div class="dropdown mb-2 me-2">
            <button class="btn btn-secondary dropdown-toggle align-items-center fixed-width" type="button" id="dropdown<%= letter %>" data-bs-toggle="dropdown" aria-expanded="false" data-user-buttons-target="letter" data-letter="<%= letter %>">
              <%= letter %>
              <span data-user-buttons-target="count" data-letter="<%= letter %>" class="badge rounded-circle bg-success bg-opacity-25 ms-2"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdown<%= letter %>">
              <% users.each do |user| %>
                <li>
                  <label class="dropdown-item user-button" data-action="click->user-buttons#toggle" data-user-buttons-target="button" data-letter="<%= letter %>">
                    <input type="checkbox" name="task[shared_user_ids][]" value="<%= user.id %>" autocomplete="off" <%= 'checked' if @task.shared_user_ids.include?(user.id) %> hidden>
                    <%= user.email %>
                  </label>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="text-center mb-10">
    <%= link_to t('tasks.link.back'), personal_tasks_path, class: "btn btn-secondary" %>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render "shared/errors_any", model: @task %>

<h1><%= t('tasks.headers.edit_task') %></h1>

<%= render 'form', task: @task%>

app/views/tasks/new.html.erb
<%= render "shared/errors_any", model: @task %>

<h1><%= t('tasks.headers.new_task') %></h1>

<%= render 'form', task: @task%>

app/views/tasks/personal.html.erb
<h1 class="mb-4"><%= t('tasks.headers.personal_tasks') %></h1>

<%= render 'shared/filter_task_form', url: personal_tasks_path %>

<div class="col-auto mb-3 d-flex align-items-start gap-3">
  <button id="showCalendarButton" class="btn btn-primary"><%= t('tasks.headers.show_calendar') %></button>
  <%= link_to t('tasks.link.group_tasks'), group_tasks_path, class: "btn btn-success text-decoration-none" %>
  <%= link_to t('tasks.link.update_tasks'), request.path, class: "btn btn-warning text-decoration-none" %>
</div>

<%= render 'shared/task_item' %>

app/views/tasks/show.html.erb
<h1 class="mb-4" style="font-size: 2rem;"><%= t('tasks.headers.task_details') %></h1>

<div class="card shadow-sm mb-4">
  <div class="card-body">
    <div class="row mb-4">
      <div class="col-md-6">
        <strong class="fs-5"><%= t('tasks.headers.title') %>:</strong>
        <span class="ms-3 text-muted fs-5"><%= @task.title %></span>
      </div>
      <div class="col-md-6">
        <strong class="fs-5"><%= t('tasks.headers.priority') %>:</strong>
        <span class="ms-3 badge bg-<%= @task.priority == 'high' ? 'danger' : @task.priority == 'medium' ? 'warning' : 'secondary' %> fs-5">
          <%= t("enums.task.priority.#{@task.priority}") %>
        </span>
      </div>
    </div>

    <div class="row mb-4">
      <div class="col-md-6">
        <strong class="fs-5"><%= t('tasks.headers.start_time') %>:</strong>
        <span class="ms-3 text-muted fs-5"><%= format_datetime(@task.start_time) %></span>
      </div>
      <div class="col-md-6">
        <strong class="fs-5"><%= t('tasks.headers.end_time') %>:</strong>
        <span class="ms-3 text-muted fs-5"><%= format_datetime(@task.end_time) %></span>
      </div>
    </div>

    <div class="row mb-4">
      <div class="col-md-6">
        <strong class="fs-5"><%= t('tasks.headers.founder') %>:</strong>
        <span class="badge bg-success ms-3 fs-5"><%= @task.author.email %></span>
      </div>
      <div class="col-md-6">
        <strong class="fs-5"><%= t('tasks.headers.status') %>:</strong>
        <span class="ms-3 badge bg-<%= @task.status == 'completed' ? 'success' : @task.status == 'in_progress' ? 'primary' : 'secondary' %> fs-5">
          <%= t("enums.task.status.#{@task.status}") %>
        </span>
      </div>
    </div>

    <div class="mb-4">
      <strong class="fs-5"><%= t('tasks.show.related.groups') %></strong>
      <% if @task.groups.any? %>
        <div class="mt-3">
          <% @task.groups.each do |group| %>
            <div class="mb-2">
              <span class="badge bg-info fs-5"><%= group.name %> (群組)：</span>
              <div class="ms-3 mt-2">
                <% group.users.where.not(id: current_user.id).each do |user| %>
                  <div class="badge email-overflow bg-primary fs-5 mb-2"><%= user.email %></div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>
        <span class="ms-3 text-muted fs-5"><%= t('tasks.show.no_related_groups') %></span>
      <% end %>
    </div>
    
    <div class="mb-4">
      <strong class="fs-5"><%= t('tasks.show.related.users') %></strong>
      <% associated_users = @task.shared_users.where.not(id: current_user.id) %>
      <% if associated_users.any? %>
        <div class="mt-3">
          <% associated_users.each do |user| %>
            <span class="badge email-overflow bg-primary me-3 fs-5 mb-2"><%= user.email %></span>
          <% end %>
        </div>
      <% else %>
        <span class="ms-3 text-muted fs-5"><%= t('tasks.show.no_sharer') %></span>
      <% end %>
    </div>

    <div class="mb-4">
      <strong class="fs-5"><%= t('tasks.headers.tags') %>:</strong>
      <div class="d-flex flex-wrap mt-2">
        <% @task.tags.each do |tag| %>
          <span class="badge bg-warning me-2 fs-5 mb-2">#<%= tag.name %></span>
        <% end %>
      </div>
    </div>

    <div class="mb-4">
      <strong class="fs-5"><%= t('tasks.headers.content') %>:</strong>
      <div class="mt-3 p-3 bg-light rounded border fs-5"><%= @task.content %></div>
    </div>
  </div>
</div>

<div class="">
  <%= link_to t('tasks.link.edit'), edit_task_path(@task), class: "btn btn-primary" %>
  <%= link_to t('tasks.link.back'), personal_tasks_path, class: "btn btn-secondary" %>
  <% if @task.file.attached? %>
    <button id="view-file-button" class="btn btn-info"
            data-file-type="<%= @task.file.content_type %>"
            data-file-url="<%= rails_blob_path(@task.file, disposition: "inline") %>">
      <%= t('tasks.link.view_file') %>
    </button>
    <%= link_to t('tasks.link.download_file'), rails_blob_path(@task.file, disposition: "attachment"), class: "btn btn-success" %>
  <% end %>
</div>