config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|zh-TW/ do
    resources :users, only: %i[new create edit update]
    namespace :admin do
      resources :users, only: %i[index edit update destroy]
    end
    resources :tasks, except: %i[index] do
      collection do
        get :personal
        post :sort
      end
      member do
        patch :update_importance
      end
    end
    resources :group_tasks, only: %i[index]

    resources :notifications, only: %i[index] do
      member do
        patch :mark_as_read
      end
    end

    resources :groups, except: %i[show] do
      delete 'remove_user', on: :member
    end

    resources :reports, only: [] do
      collection do
        get :tag_usage
      end
    end

    root 'tasks#personal'

    get 'signup', to: 'users#new'
    post 'signup', to: 'users#create'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    get '/profile/edit', to: 'users#edit_profile', as: :edit_profile
    patch '/profile', to: 'users#update_profile', as: :update_profile
  end
  get '', to: redirect('/%<locale>s'), defaults: { locale: I18n.default_locale }
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  acts_as_paranoid
  belongs_to :user
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :group_tasks, dependent: :destroy
  has_many :tasks, through: :group_tasks, dependent: :destroy

  def self.grouped_by_letter
    order(:name).group_by { |group| group.name.present? ? group.name[0].upcase : '#' }
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

# This controller manages the users within the admin namespace.
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[edit update destroy]
  before_action :set_users_by_letter, only: %i[new create edit update]

  def index
    @groups = current_user.groups.uniq
    to_creat_group
    return if params[:id].blank?

    @selected_group = current_user.groups.find_by(id: params[:id])
    @tasks = @selected_group.tasks
  end

  def new
    @group = current_user.groups.new
  end

  def edit; end

  def create
    @group = current_user.groups.new(group_params)
    @group.user = current_user

    if insufficient_members?(group_params[:user_ids])
      flash.now[:alert] = t('alert.member_count_insufficient')
      render :new and return
    end

    if @group.save
      add_current_user_to_group
      redirect_to groups_path, notice: t('.success')
    else
      render :new, alert: t('alert.creation_failed')
    end
  end

  def update
    updated_user_ids = (params[:group][:user_ids] || []).map(&:to_i)

    updated_user_ids << @group.user.id unless updated_user_ids.include?(@group.user.id)
    updated_user_ids << current_user.id unless updated_user_ids.include?(current_user.id)

    if @group.update(group_params.merge(user_ids: updated_user_ids))
      redirect_to groups_path(id: @group.id), notice: t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path, notice: t('.success')
  end

  def remove_user
    @group = Group.find(params[:id])
    user = User.find(params[:user_id])

    if user == @group.user
      redirect_to groups_path(id: @group.id), alert: t('.cannot_remove_leader')
    elsif @group.users.include?(user)
      @group.users.delete(user)
      redirect_to groups_path(id: @group.id), notice: t('.success', email: user.email)
    else
      redirect_to groups_path(id: @group.id), alert: t('.failure')
    end
  end

  private

  def set_group
    @group = current_user.groups.find_by(id: params[:id])
    render file: Rails.public_path.join('404.html').to_s, status: :not_found if @group.nil?
  end

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_users_by_letter
    @users_by_letter = User.where.not(id: current_user.id)
                           .order(:email)
                           .group_by { |user| user.email[0].upcase }
  end

  def insufficient_members?(user_ids)
    selected_user_ids = (user_ids || []).compact_blank
    total_members = selected_user_ids.size + 1
    total_members < 2
  end

  def add_current_user_to_group
    @group.users << current_user unless @group.users.include?(current_user)
  end

  def to_creat_group
    return unless @groups.empty?

    redirect_to new_group_path, alert: t('groups.alert.no_groups_found')
    nil
  end
end

app/views/groups/_form.html.erb
<%= form_with model: @group, local: true do |form| %>
  <div class="mb-3">
    <%= form.label :name, t('groups.form.name'), class: "form-label" %>
    <%= form.text_field :name, class: "form-control", placeholder: t('groups.placeholder.input_group_name') %>
  </div>
  
  <div class="align-items-center mb-3" data-controller="user-buttons">
    <div class="mb-3">
      <p><%= t('users.form.choose_share_with_other_users') %></p>
    </div>
    <span class="btn btn-success btn-sm">
      <%= t('users.form.selected') %> <span data-user-buttons-target="totalCount" class="fw-bold"><%= @group.user_ids.size %></span> <%= t('users.form.peoples') %>
    </span>
    <button class="btn btn-danger btn-sm ms-1" data-action="click->user-buttons#clearAll"><%= t('users.form.clear_all_selections') %></button>
    
    <div class="mt-3">
      <div class="d-flex flex-wrap">
        <% @users_by_letter.each do |letter, users| %>
          <div class="dropdown mb-2 me-2" style="width: 95px;">
            <button class="btn btn-secondary dropdown-toggle w-100 text-center align-items-center fixed-width" type="button" id="dropdown<%= letter %>" data-bs-toggle="dropdown" aria-expanded="false" data-user-buttons-target="letter" data-letter="<%= letter %>">
              <%= letter %>
              <span data-user-buttons-target="count" data-letter="<%= letter %>" class="badge rounded-circle bg-success bg-opacity-25 ms-2"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdown<%= letter %>">
              <% users.each do |user| %>
                <li>
                  <label class="dropdown-item d-flex align-items-center user-button" data-action="click->user-buttons#toggle" data-user-buttons-target="button" data-letter="<%= letter %>">
                    <input type="checkbox" name="group[user_ids][]" value="<%= user.id %>" autocomplete="off" <%= 'checked' if @group.user_ids.include?(user.id) %> hidden>
                    <%= user.email %>
                  </label>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= form.submit class: "btn btn-primary" %>
  <%= link_to t('tasks.link.back'), groups_path, class: "btn btn-secondary" %>
<% end %>

app/views/groups/edit.html.erb
<h1>編輯群組</h1>

<% if @group.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
    <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form', group: @group%>

app/views/groups/index.html.erb
<h1 class="mb-4"><%= t('groups.headers.index') %></h1>
<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        <strong><%= t('groups.index.group_list') %></strong>
      </div>
      <ul class="list-group list-group-flush">
        <% @groups.each do |group| %>
          <li class="list-group-item <%= 'active bg-success' if group == @selected_group %>">
            <%= link_to groups_path(id: group.id), class: "text-decoration-none d-block fw-bold #{group == @selected_group ? 'bg-success text-white' : 'bg-light text-dark'}" do %>
              <%= group.name %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="min-group-card col-md-8">
    <% if @selected_group %>
      <div class="card shadow-sm">
        <div class="card-body">
          <h3 class="card-title border-bottom pb-3 mb-4 text-primary"><%= @selected_group.name %></h3>
          
          <div class="mb-4">
            <h5 class="fw-bold text-secondary"><%= t('groups.show.group_leader') %></h5>
            <ul class="list-unstyled">
              <li class="mb-1 d-flex align-items-center">
                <i class="bi bi-person-circle me-2"></i> 
                <span class="email-overflow-group btn btn-outline-info"><%= @selected_group.user.email %></span>
              </li>
            </ul>
          </div>
          
          <div class="mb-4">
            <h5 class="fw-bold text-secondary"><%= t('groups.show.members') %></h5>
            <ul class="list-unstyled">
              <% @selected_group.users.reject { |user| user == current_user }.each do |user| %>
                <li class="mb-2 d-flex align-items-center justify-content-between">
                  <div class="d-flex align-items-center">
                    <i class="bi bi-person-circle me-2"></i>
                    <span class="btn btn-outline-info me-2"><%= user.email %></span>
                    <%= link_to '✕', remove_user_group_path(@selected_group, user_id: user.id), 
                                data: { turbo_method: :delete, turbo_confirm: t('groups.confirm.remove_user') }, 
                                class: "btn btn-outline-danger btn-sm" %>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
          <div class="d-flex gap-2">
            <%= link_to t('groups.link.edit'), edit_group_path(@selected_group), class: "btn btn-warning" %>
            <%= link_to t('groups.link.delete'), @selected_group, data: { turbo_confirm: t('groups.confirm.delete'), turbo_method: :delete }, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    <% else %>
      <div class="alert alert-info" role="alert">
        <p><%= t('groups.remind.select_group') %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<h1><%= t('groups.headers.new') %></h1>

<%= render 'form', group: @group%>