config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|zh-TW/ do
    resources :users, only: %i[new create edit update]
    namespace :admin do
      resources :users, only: %i[index edit update destroy]
    end
    resources :tasks, except: %i[index] do
      collection do
        get :personal
        post :sort
      end
      member do
        patch :update_importance
      end
    end
    resources :group_tasks, only: %i[index]

    resources :notifications, only: %i[index] do
      member do
        patch :mark_as_read
      end
    end

    resources :groups, except: %i[show] do
      delete 'remove_user', on: :member
    end

    resources :reports, only: [] do
      collection do
        get :tag_usage
      end
    end

    root 'tasks#personal'

    get 'signup', to: 'users#new'
    post 'signup', to: 'users#create'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    get '/profile/edit', to: 'users#edit_profile', as: :edit_profile
    patch '/profile', to: 'users#update_profile', as: :update_profile
  end
  get '', to: redirect('/%<locale>s'), defaults: { locale: I18n.default_locale }
end

app/views/shared/_errors_any.html.erb
<% if model.errors.any? %>
  <div id="flash-errors" data-errors="<%= model.errors.full_messages.to_json %>"></div>
<% end %>

app/views/shared/_filter_task_form.html.erb
<%= form_with url: url, method: :get, local: true, class: "row g-3 mb-4" do |form| %>
  <div class="col-auto">
    <%= form.label :status, t('tasks.filters.status'), class: "form-label" %>
    <%= form.select :status, Task.statuses.keys.map { |status| [t("enums.task.status.#{status}"), status] }, { include_blank: true, selected: params[:status] }, class: "form-select" %>
  </div>

  <div class="col-auto">
    <%= form.label :query, t('tasks.filters.keyword'), class: "form-label" %>
    <%= form.text_field :query, value: params[:query], class: "form-control", placeholder: t('tasks.form.placeholder.query_title') %>
  </div>

  <div class="col-auto">
    <%= form.label :tag, t('tasks.filters.tag'), class: "form-label" %>
    <%= form.collection_select :tag_id, Tag.order(:name), :id, :name, { include_blank: true, selected: params[:tag_id] }, { class: "form-select" } %>
  </div>

  <div class="col-auto align-self-end">
    <%= form.submit t('tasks.filters.filter'), class: "btn btn-primary" %>
  </div>
  
  <div class="col-auto align-self-end">
    <%= link_to t('tasks.link.new_task'), new_task_path, class: "btn btn-success mt-3 text-decoration-none" %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] || flash[:alert] %>
  <div id="flash-message"
       data-type="<%= flash[:notice] ? 'success' : 'error' %>"
       data-message="<%= j(flash[:notice] || flash[:alert]) %>">
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-white mt-auto py-3">
  <div class="container text-center">
    <div class="row">
      <div class="col-md-4">
        <h5><%= t('footer.about') %></h5>
        <p><%= t('footer.about_me') %></p>
      </div>
      <div class="col-md-4">
        <h5><%= t('footer.quick_link') %></h5>
        <ul class="list-unstyled">
          <li><%= link_to t('footer.contact_me'), 'mailto:kauia96@gmail.com', class: 'text-white' %></li>
          <li><%= link_to t('footer.privacy_policy'), '#', class: 'text-white' %></li>
          <li><%= link_to t('QBlog'), 'https://qblog-thrumming-snow-411.fly.dev/', class: 'text-white' %></li>
        </ul>
      </div>
      <div class="col-md-4">
        <h5><%= t('footer.socia_media') %></h5>
        <a href="#" class="text-white me-2"><i class="bi bi-facebook"></i></a>
        <a href="#" class="text-white me-2"><i class="bi bi-twitter"></i></a>
        <a href="#" class="text-white"><i class="bi bi-instagram"></i></a>
      </div>
    </div>
    <hr class="bg-light">
    <p class="mb-0">&copy; <%= Time.current.year %> Qkauia </p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Q'Tasks", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <% if current_user&.role == "admin" %>
          <li class="nav-item">
            <%= link_to t('navbar.admin_interface'), admin_users_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to t('tasks.link.english'), url_for(locale: 'en'), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t('tasks.link.chinese'), url_for(locale: 'zh-TW'), class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to t('tasks.link.new_task'), new_task_path, class: "btn btn-success text-decoration-none" %>
        </li>
        <li class="nav-item">
          <%= link_to t('groups.links.create_group'), new_group_path, class: "btn btn-success text-decoration-none" %>
        </li>
        <% if current_user %>
          <!-- Notification Dropdown -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= t('navbar.notification') %>
              <% if @unread_count.to_i > 0 %>
                <span class="badge bg-danger"><%= @unread_count %></span>
              <% end %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if @unread_count.to_i > 0 %>
                <% notifications_to_display = @notifications.first(5) %>
                <% notifications_to_display.each do |notification| %>
                  <li class="dropdown-item">
                    <h4 class="fw-bold task-titile-overflow-group"><%= notification.task.title %></h4>
                    <%= notification.message %>
                    <div class="mt-2">
                      <%= link_to t('navbar.notification_links.mark_as_read'), mark_as_read_notification_path(notification), data: { turbo_method: :patch }, class: "btn btn-sm btn-outline-primary" %>
                      <% if notification.task.present? %>
                        <%= link_to t('navbar.notification_links.view_tasks'), task_path(notification.task), class: "btn btn-sm btn-outline-secondary ms-2" %>
                      <% else %>
                        <span class="text-muted"><%= t('navbar.notification_messages.task_removed') %></span>
                      <% end %>
                    </div>
                  </li>
                  <li><hr class="dropdown-divider"></li>
                <% end %>

                <!-- 顯示"更多通知"的連結，如果未讀通知超過5條 -->
                <% if @unread_count > 5 %>
                  <li class="dropdown-item text-center">
                    <%= link_to t('navbar.notification_links.view_all_notifications'), notifications_path %>
                  </li>
                <% end %>
              <% else %>
                <li class="dropdown-item text-muted"><%= t('navbar.notification_messages.no_notification') %></li>
              <% end %>
            </ul>
          </li>
          <!-- User Links with Avatar -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.avatar.present? %>
                <%= image_tag current_user.avatar.url(:thumb), class: "rounded-circle me-2", width: 30, height: 30 %>
              <% else %>
                <%= image_tag "default_avatar.jpg", class: "rounded-circle me-2", width: 30, height: 30 %>
              <% end %>
              <%= current_user.email %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
              <li>
                <%= link_to t('users.headers.update_password'), edit_user_path(current_user), class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to t('navbar.update_avatar'), edit_profile_path, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to t('navbar.my_tasks'), personal_tasks_path, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to t('navbar.my_groups'), groups_path, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to t('navbar.logout'), logout_path, class: "dropdown-item", data: { turbo_method: "delete", turbo_confirm: t('users.confirm.logout') } %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('navbar.login'), login_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_task_item.html.erb
<h3><%= t('tasks.headers.all_tasks') %></h3>
<table class="table table-striped">
  <thead class="d-md-table-header-group">
    <tr>
      <th class="col-6 col-md-2"><%= t('tasks.headers.title') %><%= sort_link('title', '  ▼') %></th>
      <th class="col-2 col-md-2"><%= t('tasks.headers.priority') %><%= sort_link('priority', '  ▼') %></th>
      <th class="col-4 col-md-2"><%= t('tasks.headers.status') %></th>
      <th class="col-12 col-md-2"><%= t('tasks.headers.start_time') %><%= sort_link('start_time', '  ▼') %></th>
      <th class="col-12 col-md-2"><%= t('tasks.headers.end_time') %><%= sort_link('end_time', '  ▼') %></th>
      <th class="col-12 col-md-2"><%= t('tasks.headers.group') %></th>
      <th class="col-12 col-md-2"><%= t('tasks.headers.shared_count') %><%= sort_link('shared_count', '  ▼') %></th>
      <th class="col-12 col-md-2"><%= t('tasks.headers.actions') %></th>
    </tr>
  </thead>
  <tbody id="normal-tasks" class="table-container">
    <% if @tasks.any? %>
      <% @tasks.each do |task| %>
        <tr data-task-id="<%= task.id %>">
          <td class="col-6 col-md-2">
            <span class="d-md-none"><%= t('tasks.headers.title') %>：</span>
            <%= link_to task.title, task_path(task.id), class: "text-decoration-none task-title", title: task.title %>
          </td>
          <td class="col-6 col-md-2">
            <span class="d-md-none"><%= t('tasks.headers.priority') %>：</span>
            <%= t("enums.task.priority.#{task.priority}") %>
          </td>
          <td class="col-6 col-md-2">
            <span class="d-md-none"><%= t('tasks.headers.status') %>：</span>
            <%= t("enums.task.status.#{task.status}") %>
          </td>
          <td class="col-6 col-md-2">
            <span class="d-md-none"><%= t('tasks.headers.start_time') %>：</span>
            <%= format_datetime(task.start_time) %>
          </td>
          <td class="col-6 col-md-2">
            <span class="d-md-none"><%= t('tasks.headers.end_time') %>：</span>
            <%= format_datetime(task.end_time) %>
          </td>
          <td class="col-12 col-md-2">
              <span class="d-md-none"><%= t('tasks.headers.group') %>：</span>
            <% if task.groups.any? %>
              <%= task.groups.map(&:name).join(', ') %>
            <% else %>
              <p><%= t('tasks.headers.no_group') %></p>
            <% end %>
          </td>
          <td class="col-12 col-md-2">
            <% shared_count = task.shared_count %>
            <span class="d-md-none"><%= t('tasks.headers.shared_count') %>：</span>
            <% case shared_count %>
            <% when 1..5 %>
              <%= '☺' * shared_count %>
            <% when 6..Float::INFINITY %>
              <%= '☺☺☺☺☺..more' %>
            <% else %>
              <%= '&nbsp;'.html_safe %>
            <% end %>
          </td>
          <td class="col-12 col-md-2">
            <%= link_to t('tasks.link.show'), task, class: "btn btn-info btn-sm text-decoration-none" %>
            <%= link_to t('tasks.link.edit'), edit_task_path(task), class: "btn btn-warning btn-sm text-decoration-none" %>
            <%= link_to t('tasks.link.delete'), task, data: { turbo_method: "delete", turbo_confirm: t('tasks.destroy.confirm') }, class: "btn btn-danger btn-sm text-decoration-none" %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="8" class="text-center"><%= t('tasks.headers.no_task') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="d-flex justify-content-center">
  <%= paginate @tasks %>
</div>

<h3 class="mt-2"><%= t('tasks.headers.important_tasks') %></h3>
<table class="table table-striped">
  <thead class="d-md-table-header-group">
    <tr>
      <th class="col-6 col-md-2"><%= t('tasks.headers.title') %><%= sort_link('title', '  ▼') %></th>
      <th class="col-2 col-md-1"><%= t('tasks.headers.priority') %><%= sort_link('priority', '  ▼') %></th>
      <th class="col-4 col-md-2"><%= t('tasks.headers.status') %></th>
      <th class="col-12 col-md-2"><%= t('tasks.headers.start_time') %><%= sort_link('start_time', '  ▼') %></th>
      <th class="col-12 col-md-2"><%= t('tasks.headers.end_time') %><%= sort_link('end_time', '  ▼') %></th>
      <th class="col-12 col-md-2"><%= t('tasks.headers.group') %></th>
      <th class="col-12 col-md-1"><%= t('tasks.headers.shared_count') %><%= sort_link('shared_count', '  ▼') %></th>
      <th class="col-12 col-md-2"><%= t('tasks.headers.actions') %></th>
    </tr>
  </thead>
  <tbody id="important-tasks">
    <% if @important_tasks.any? %>
      <% @important_tasks.each do |task| %>
        <tr data-task-id="<%= task.id %>">
          <td class="col-6 col-md-2">
            <span class="d-md-none"><%= t('tasks.headers.title') %>：</span>
            <%= link_to task.title, task_path(task.id), class: "text-decoration-none task-title", title: task.title %>
          </td>
          <td class="col-6 col-md-2">
            <span class="d-md-none"><%= t('tasks.headers.priority') %>：</span>
            <%= t("enums.task.priority.#{task.priority}") %>
          </td>
          <td class="col-6 col-md-2">
            <span class="d-md-none"><%= t('tasks.headers.status') %>：</span>
            <%= t("enums.task.status.#{task.status}") %>
          </td>
          <td class="col-6 col-md-2">
            <span class="d-md-none"><%= t('tasks.headers.start_time') %>：</span>
            <%= format_datetime(task.start_time) %>
          </td>
          <td class="col-6 col-md-2">
            <span class="d-md-none"><%= t('tasks.headers.end_time') %>：</span>
            <%= format_datetime(task.end_time) %>
          </td>
          <td class="col-12 col-md-2">
              <span class="d-md-none"><%= t('tasks.headers.group') %>：</span>
            <% if task.groups.any? %>
              <%= task.groups.map(&:name).join(', ') %>
            <% else %>
              <p><%= t('tasks.headers.no_group') %></p>
            <% end %>
          </td>
          <td class="col-12 col-md-1">
            <% shared_count = task.shared_count %>
            <span class="d-md-none"><%= t('tasks.headers.shared_count') %>：</span>
            <% case shared_count %>
            <% when 1..5 %>
              <%= '☺' * shared_count %>
            <% when 6..Float::INFINITY %>
              <%= '☺☺☺☺☺..more' %>
            <% else %>
              <%= '&nbsp;'.html_safe %>
            <% end %>
          </td>
          <td class="col-12 col-md-2">
            <%= link_to t('tasks.link.show'), task, class: "btn btn-info btn-sm text-decoration-none" %>
            <%= link_to t('tasks.link.edit'), edit_task_path(task), class: "btn btn-warning btn-sm text-decoration-none" %>
            <%= link_to t('tasks.link.delete'), task, data: { turbo_method: "delete", turbo_confirm: t('tasks.destroy.confirm') }, class: "btn btn-danger btn-sm text-decoration-none" %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="8" class="text-center"><%= t('tasks.headers.no_task') %></td>
      </tr>
    <% end %>
  </tbody>
</table>